<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.198">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Phonologie der deutschen Sprache - 4&nbsp; Aufgabenbereich der Phonemik</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./artikulation.html" rel="next">
<link href="./phonetik.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script async="" src="https://hypothes.is/embed.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="style.css">
<link rel="stylesheet" href="TMwR.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Aufgabenbereich der Phonemik</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Phonologie der deutschen Sprache</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/tpetric7/textlinguistik-2022" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
    <a href="" title="Download" id="sidebar-tool-dropdown-0" class="sidebar-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-download"></i></a>
    <ul class="dropdown-menu" aria-labelledby="sidebar-tool-dropdown-0">
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="./Phonologie-der-deutschen-Sprache.pdf">
            <i class="bi bi-bi-file-pdf pe-1"></i>
          Download PDF
          </a>
        </li>
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="./Phonologie-der-deutschen-Sprache.epub">
            <i class="bi bi-bi-journal pe-1"></i>
          Download ePub
          </a>
        </li>
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="./Phonologie-der-deutschen-Sprache.docx">
            <i class="bi bi-bi-file-word pe-1"></i>
          Download Docx
          </a>
        </li>
    </ul>
    <a href="" title="Share" id="sidebar-tool-dropdown-1" class="sidebar-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-share"></i></a>
    <ul class="dropdown-menu" aria-labelledby="sidebar-tool-dropdown-1">
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
            <i class="bi bi-bi-twitter pe-1"></i>
          Twitter
          </a>
        </li>
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
            <i class="bi bi-bi-facebook pe-1"></i>
          Facebook
          </a>
        </li>
    </ul>
  <a href="" class="quarto-color-scheme-toggle sidebar-tool" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle sidebar-tool" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">.</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">Vorwort</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Grundbegriffe und Systematik</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Einführung</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./gegenstand.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Gegenstand und Sinn der Phonologie</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./phonetik.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Aufgabenbereich der Phonetik</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./phonemik.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Aufgabenbereich der Phonemik</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./artikulation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Artikulatorische Phonetik</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./phonotaktik.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Phonotaktik</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prozesse.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Phonologische Prozesse</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prosodie.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Prosodie</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Aussprachepraxis im Sprachlabor</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./wortakzent.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Wortakzentuierung [#sec-wortakzent]</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./satzakzent.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Akzentuierung von Phrasen [#sec-satzakzent]</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./satzmelodie.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Melodiebewegungen in Äußerungen [#sec-satzmelodie]</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./vokale.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Vokale im Einzelnen [#sec-vokale]</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./konsonanten.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Konsonanten im Einzelnen [#sec-konsonanten]</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Summary</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
  <li><a href="#opposition" id="toc-opposition" class="nav-link active" data-scroll-target="#opposition"><span class="toc-section-number">4.0.1</span>  Opposition</a></li>
  <li><a href="#variation" id="toc-variation" class="nav-link" data-scroll-target="#variation"><span class="toc-section-number">4.0.2</span>  Variation</a></li>
  <li><a href="#distribution" id="toc-distribution" class="nav-link" data-scroll-target="#distribution"><span class="toc-section-number">4.0.3</span>  Distribution</a></li>
  <li><a href="#phonem--und-silbeninventare" id="toc-phonem--und-silbeninventare" class="nav-link" data-scroll-target="#phonem--und-silbeninventare"><span class="toc-section-number">4.0.4</span>  Phonem- und Silbeninventare</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/tpetric7/textlinguistik-2022/edit/main/phonemik.qmd" class="toc-action">Seite editieren</a></p><p><a href="https://github.com/tpetric7/textlinguistik-2022/issues/new" class="toc-action">Problem melden</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title d-none d-lg-block"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Aufgabenbereich der Phonemik</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Die Phonemik erforscht Lautsysteme. Ihre Aufgabe besteht also darin, “die Beziehungen der Laute einer gegebenen Sprache zueinander zu analysieren, um so das Lautsystem zu beschreiben.” (SSM 1: 2) In der Tagmemik, einer wichtigen Richtung des amerikanischen Strukturalismus (Hauptvertreter K. L. Pike), werden alle sprachlichen Einheiten unter drei Gesichtspunkten untersucht:</p>
<ul>
<li><p>Opposition,</p></li>
<li><p>Variation und</p></li>
<li><p>Distribution.</p></li>
</ul>
<section id="opposition" class="level3" data-number="4.0.1">
<h3 data-number="4.0.1" class="anchored" data-anchor-id="opposition"><span class="header-section-number">4.0.1</span> Opposition</h3>
<p>Die Wortpaare (oder besser: Lautfolgen) in den folgenden Beispielen unterscheiden sich jeweils nur durch einen Laut. Diejenigen Laute, die sich voneinander unterscheiden (also distinktive phonetische Merkmale aufweisen), stehen in Opposition (nach einer anderen Ausdrucksweise “in paradigmatischem Kontrast”) zueinander, womit gesagt sein soll, daß sie bedeutungsunterscheidende Funktion haben.</p>
<ol start="8" type="1">
<li><p>Deutsch: [lant] “Land” vs.&nbsp;[vant] “Wand”<br>
<span class="math display">\[
\frac{[lant]}{[vant]}
\]</span></p></li>
<li><p>Slowenisch: [ko:s] “kos” (Stück) vs.&nbsp;[vo:s] “voz” (Wagen)<br>
<span class="math display">\[
\frac{[ko:s]}{[vo:s]}
\]</span></p></li>
<li><p>Englisch: [fɪʃ] “fish” (Fisch) vs.&nbsp;[dɪʃ] “dish” (Gefäß).<br>
<span class="math display">\[
\frac{[fɪʃ]}{[dɪʃ]}
\]</span></p></li>
</ol>
<p>Somit müssen [l] und [v] im deutschen Beispiel, [k] und [v] im slowenischen und [f] und [d] im englischen jeweils zwei Phonemen zugeordnet werden: in (8) den Phonemen /l/ und /v/, in (9) den Phonemen /k/ und /v/ und in (10) den Phonemen /f/ und /d/.</p>
<p>Opposition ist eine <strong>paradigmatische Beziehung</strong>, Kontrast dagegen eine syntagmatische. Eine Opposition ist eine <strong>symmetrische Beziehung</strong> zwischen sprachlichen Lauten. In den Lautfolgen der Wörter &lt;fast&gt; und &lt;Rast&gt; steht der Obstruent [f] in Opposition zum Liquid [R] und umgekehrt. <strong>Kontrast</strong> ist dagegen eine <strong>asymmetrische Beziehung</strong> zwischen sprachlichen Lauten (vgl. Eisenberg 1998: 88). In einer Form wie &lt;Frau&gt; steht der Liquid /r/ in Kontrast zum Obstruenten /f/, während der Obstruent /f/ in dieser Position nicht in Kontrast zum Liquid /r/ stehen kann, da eine (einsilbige) Form wie [rfao] nicht vorkommt. In anderen Umgebungen kontrastiert der Obstruent durchaus mit dem Liquid<em>,</em> z.B. in [Wurf], aber der Liquid nicht mit dem Obstruenten [Wufr]. Beide Lautfolgen (d.h. [fr] und [rf]) sind somit an unterschiedliche Kontexte gebunden. Der Kontrastbegriff ist die Grundlage für die Ermittlung der <strong>phonotaktischen Kombinationsmöglichkeiten</strong> (Lautkombinatorik) in einer Sprache. Als operationale Verfahren zur Ermittlung einer <strong>Opposition</strong> verwenden wir die <strong>Kommutations- oder Substitutionsprobe</strong>, zur Ermittlung eines <strong>Kontrastes</strong> dagegen die <strong>Permutations- oder Verschiebeprobe</strong>. Die in den oben angeführten Beispielen durchgeführte Kommutationsprobe nennt man übrigens auch den <strong>Minimalpaartest</strong>. (vgl. auch in der Dudengrammatik <span class="citation" data-cites="drosdowski1995duden">(<a href="references.html#ref-drosdowski1995duden" role="doc-biblioref">Drosdowski 1995</a> : 32-33)</span> über die funktionalen Eigenschaften Opposition und Kontrast am Beispiel des Wortes &lt;Markt&gt;).</p>
</section>
<section id="variation" class="level3" data-number="4.0.2">
<h3 data-number="4.0.2" class="anchored" data-anchor-id="variation"><span class="header-section-number">4.0.2</span> Variation</h3>
<p>Zwei verschiedene Laute einer Sprache stehen nicht immer in Opposition zueinander. Können verschiedene Laute nicht als Phoneme eingeordnet werden, dann besteht die Möglichkeit, dass es sich um Varianten eines einzigen Phonems (auch <strong>Allophone</strong> genannt) handelt. <strong>Phonemvariation</strong> kann <strong>frei</strong> oder <strong>stellungsgebunden</strong> sein.</p>
<ol start="11" type="1">
<li>Deutsch: [reː.ɡən] vs.&nbsp;[Reː.ɡən] vs.&nbsp;[ʁeː.ɡən] “Regen”</li>
<li>Slowenisch: [ta.nək] tanek “dünn”, masc. vs.&nbsp;[taŋ.ka] tanka “dünn”, fem.</li>
</ol>
<p>Im deutschen Wort &lt;Regen&gt; (11) kann das Phonem /r/ verschiedentlich realisiert werden, ohne dadurch die Bedeutung der Lautfolge zu verändern. Im Deutschen sind die drei r-Laute [r], [R] und [ʁ] freie Varianten eines einzigen Phonems, d.h. <strong>fakultative Allophone</strong> des Phonems /r/. Auch im Slowenischen können die oben genannten r-Laute frei variieren, ohne die Wortbedeutung zu verändern. In der slowenischen Standardsprache ist allerdings im Unterschied zur deutschen nur das alveolar apikale [r] üblich, das auch als Zungenspitzen-r bekannt ist. In einer anderen Sprache können verschieden realisierte r-Laute allerdings auch in Opposition zueinander stehen und somit als zwei verschiedene Phoneme eingeordnet werden (z.B. im Spanischen ein langer und ein kurzer r-Laut).</p>
<p>Das Phonem /n/ wird im Slowenischen (12) je nach Lautumgebung als dental-alveolares [n] oder als velar-postdorsales [ŋ] realisiert. Vor einem Vokal wird beispielsweise die erste Variante ausgesprochen, vor den velaren Obstruenten [k], [g] und [x] die letztere (Toporišič <sup>2</sup>1991: 71). Das Phonem /n/ weist demnach im Slowenischen (neben anderen hier nicht aufgeführten) zumindest zwei <strong>stellungsbedingte Allophone</strong> (positionsabhängige, stellungsgebundene oder kombinatorische Allophone) auf. Im Slowenischen sind die beiden Allophone <strong>komplementär verteilt</strong>, d.h. daß das [n] nicht in allen Lautumgebungen vorkommt, in denen [ŋ] auftritt, und umgekehrt.</p>
<p>Auch im Deutschen kommt der velare Nasalkonsonant [ŋ] ebenfalls nicht in allen Lautumgebungen vor (wie im Slowenischen ist er im Silbenanlaut ausgeschlossen), aber an der Silbengrenze zwischen Vokalen steht er in Opposition zum alveolaren Nasalkonsonant [n] (vgl. &lt;Wanne&gt; vs.&nbsp;&lt;Wange&gt;). Die Tatsache, dass mit Hilfe eines Minimalpaartests eine Opposition zwischen den beiden deutschen Nasalkonsonanten gefunden werden konnte, kann man als Argument für die Unterscheidung zweier Phoneme werten. Dagegen spricht, dass der velare Nasalkonsonant in weniger Lautumgebungen vorkommt als der alveolare Nasalkonsonant.</p>
<p>Der phonetische Unterschied in slowenischen Beispiel (12) ist demnach durch die Lautumgebung bestimmt. Man kann also von der lautlichen Umgebung her schließen, welchen phonetischen Wert das Phonem /n/ in dieser Umgebung hat. Somit sind die beiden Laute (Phone) im Slowenischen Varianten einer Lauteinheit (eines Phonems), und es genügt, ein einziges phonemisches Zeichen /n/ für beide phonetischen Varianten [n] und [ŋ] anzusetzen. Im Slowenischen wird dieses Verhalten auch in der Ortographie (Rechtschreibung) ausgedrückt, denn beide Realisierungsformen des Phonems werden durch das gleiche Graphem wiedergegeben (auch in Eigennamen, vgl. (13)).</p>
<ol start="13" type="1">
<li>&lt;Ana&gt; vs.&nbsp;&lt;Anka&gt;.</li>
</ol>
<p>Im Deutschen spricht die Orthographie nicht dafür, die beiden Nasalkonsonanten einem einzigen Phonem zuzuordnen, denn die beiden Laute werden im einheimischen Wortschatz durch unterschiedliche Grapheme wiedergegeben: so wird der alveolare Nasalkonsonant mit dem Graphem &lt;n&gt; wiedergegeben (wie z.B. in &lt;Biene, Wanne&gt;), während dem velaren Nasalkonsonanten das Graphem &lt;ng&gt; zugeordnet wird (wie z.B. in &lt;Wange, Klinge, Zunge&gt;). Die beiden deutschen Nasalkonsonanten könnten eher als zwei verschiedene Phoneme gewertet werden, die beiden slowenischen Nasalkonsonanten dagegen eher als ein Phonem (mit stellungsbedingter Phonemvariation).</p>
</section>
<section id="distribution" class="level3" data-number="4.0.3">
<h3 data-number="4.0.3" class="anchored" data-anchor-id="distribution"><span class="header-section-number">4.0.3</span> Distribution</h3>
<p>Beim Vergleich zweier Sprachen kann man oft feststellen, dass in beiden zwar derselbe Laut (oder zwei sehr ähnliche Laute) vorkommt, aber jeweils in unterschiedlicher Position. Der betreffende Laut hat in beiden Sprachen also eine unterschiedliche Verteilung oder Distribution. Dieser Umstand soll am Beispiel des velaren Nasalkonsonanten illustriert werden.</p>
<p>Der <strong>velare Nasalkonsonant</strong> [ŋ] kommt in der <strong>deutschen Standardsprache</strong> in den folgenden Positionen vor:</p>
<ul>
<li><p>im Wort- und Silbenauslaut nach ungespannten Vokalen (z.B. &lt;Ding, eng, Gang, Gong, Dung&gt;);</p></li>
<li><p>im Wort- und Silbenauslaut als Folge der Schwa-Tilgung und der Assimilation nach [g] und [k] in derselben Silbe (z.B. &lt;fragen, packen&gt;);</p></li>
<li><p>im Silbenauslaut vor [k] im Anlaut der nächsten Silbe (z.B. &lt;trin-ken&gt;);</p></li>
<li><p>im Silbenauslaut vor [g] im Anlaut der nächsten Silbe, aber nur in Lehnwörtern (z.B. &lt;Tan-go, Un-garn, Lin-gu-ist&gt;);</p></li>
<li><p>im Wort- und Silbeninlaut vor [k] in derselben Silbe (z.B. &lt;Schank&gt;);</p></li>
<li><p>im Inlaut als sogenanntes Silbengelenk (d.h. gleichzeitig im Auslaut der ersten Silbe und im Anlaut der zweiten) vor Schwa [ə] (z.B. &lt;hängen&gt;) oder als Folge von Assimilation vor sonantischem [l̩] (z.B. kling(e)ln).</p></li>
</ul>
<p>In der <strong>slowenischen Standardsprache</strong> tritt der <strong>velare Nasalkonsonant</strong> [ŋ] in den folgenden Positionen auf:</p>
<ul>
<li><p>im Silbenauslaut nach ungespannten Vokalen vor [g], [k] und [x] in der nächsten Silbe (z.B. &lt;An-hovo, Kon-go, Can-kar&gt;);</p></li>
<li><p>im Silbeninlaut nach ungespannten Vokalen vor [k] in derselben Silbe (z.B. &lt;tank&gt;).</p></li>
</ul>
<p>Aus dieser Gegenüberstellung ist ersichtlich, daß die <strong>Distribution</strong> des velaren Nasalkonsonanten <strong>im Slowenischen eingeschränkter</strong> ist als im Deutschen, denn im Slowenischen kann er nicht stehen:</p>
<ul>
<li><p>im Silben- oder Wortauslaut, wenn kein [k] in derselben oder der nächsten Silbe folgt;</p></li>
<li><p>im Inlaut vor Schwa [ə] oder sonantischem [l̩];</p></li>
<li><p>im Auslaut nach [g] und [k] (d.h. aufgrund von Schwa-Reduktion und regressiver Nasalassimilation an einen velaren Obstruenten wie im deutschen Verb &lt;fragen&gt;).</p></li>
</ul>
<p><strong>Tabelle 2: Distribution des Nasalkonsonaten [ŋ] im Deutschen und Slowenischen</strong></p>
<table class="table">
<colgroup>
<col style="width: 28%">
<col style="width: 50%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>Deutsch</strong></th>
<th><strong>Slowenisch</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Wort- u.</strong> <strong>Silbenanlaut</strong></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><strong>Wort- u.</strong> <strong>Silbeninlaut</strong></td>
<td>vor [k]</td>
<td>vor [k]</td>
</tr>
<tr class="odd">
<td><strong>Wortinlaut</strong> <strong>(Silbengelenk)</strong></td>
<td>vor [ə] und [l̩]</td>
<td></td>
</tr>
<tr class="even">
<td><strong>Silbenauslaut</strong></td>
<td><p>Vokal:</p>
<p>vor [k]</p></td>
<td><p>Vokal:</p>
<p>vor [k], [g], [x]</p></td>
</tr>
<tr class="odd">
<td><strong>Wortauslaut</strong></td>
<td>nach [g] und [k] in unbetonter Silbe (bei Schwa-Tilgung)</td>
<td></td>
</tr>
</tbody>
</table>
<p>&nbsp;</p>
<p>In einem Fall ist die Distribution des velaren Nasalkonsonanten im Deutschen jedoch eingeschränkter, denn im Slowenischen kann der velare Nasalkonsonant vor [x] in der nächsten Silbe auftreten, im Deutschen jedoch nicht.</p>
<p>Beide Sprachen haben u.a. gemeinsam, daß der velare Nasalkonsonant nicht im Silbenanlaut vorkommen kann. Diese Möglichkeit besteht in anderen Sprachen, z.B. im Kulunge, einer Sprache Nepals (SSM 1: 3).</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="pictures/01b_NSG_Intro_2020-10-07/wals_velar_nasal.png" class="img-fluid" style="width:100.0%"></p>
</div>
</div>
<p><a href="https://wals.info/">Wals Online</a></p>
<p>Im Rahmen der Lautdistribution wird auch die Häufigkeit des Vorkommens eines Lautes untersucht, anhand derer sich oft charakteristische Unterschiede zwischen Sprachen feststellen lassen (SSM 1: 3). So tritt z.B. der stimmhafte postalveolare Frikativ [ʒ] im Deutschen nur in wenigen Lehnwörtern auf (z.B. &lt;<u>G</u>enie, Gara<u>g</u>e&gt;) und hat daher eine eher periphere Stellung im deutschen Phonemsystem. Im Französischen oder im Slowenischen tritt dieser stimmhafte Frikativ jedoch in einer viel größeren Anzahl von Wörtern auf und gehört eher zum Kern des französischen bzw. slowenischen Phonemsystems (z.B. franz. &lt;<u>j</u>e&gt; “ich”, &lt;<u>j</u>our&gt; “Tag”, &lt;pi<u>g</u>eon&gt; “Taube”; slow. &lt;<u>ž</u>ena&gt; “(Ehe)frau”, &lt;<u>ž</u>oga&gt; “Ball”, &lt;<u>ž</u>aba&gt; “Frosch”).</p>
</section>
<section id="phonem--und-silbeninventare" class="level3" data-number="4.0.4">
<h3 data-number="4.0.4" class="anchored" data-anchor-id="phonem--und-silbeninventare"><span class="header-section-number">4.0.4</span> Phonem- und Silbeninventare</h3>
<p>Zur Orientierung sollen einige Angaben zur Phoneminventargröße herangezogen werden. In der Untersuchung von Ian Maddieson (Consonant Inventories, In: Wals 2005) findet man folgende Angaben zur <strong>Größe von Konsonanteninventaren</strong> in den Sprachen der Welt (gemeint sind Konsonantenphoneme):</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">&nbsp;</th>
<th style="text-align: center;"><strong>Consonant Inventory Size</strong></th>
<th style="text-align: center;">&nbsp;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1.</td>
<td style="text-align: center;">Small</td>
<td style="text-align: center;">91</td>
</tr>
<tr class="even">
<td style="text-align: center;">2.</td>
<td style="text-align: center;">Moderately small</td>
<td style="text-align: center;">121</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3.</td>
<td style="text-align: center;">Average</td>
<td style="text-align: center;">181</td>
</tr>
<tr class="even">
<td style="text-align: center;">4.</td>
<td style="text-align: center;">Moderately large</td>
<td style="text-align: center;">116</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5.</td>
<td style="text-align: center;">Large</td>
<td style="text-align: center;">53</td>
</tr>
<tr class="even">
<td style="text-align: center;">@</td>
<td style="text-align: center;">Total</td>
<td style="text-align: center;">562</td>
</tr>
</tbody>
</table>
<p>&nbsp;</p>
<ul>
<li><p>Die <strong>typischere Konsonanteninventargröße</strong> liegt in den unteren Zwanzigern, wobei der Mittelwert für die 562 Sprachen 22,7 beträgt, der Modus 22 und der Median 21. Konsonanteninventare in der Nähe dieser Größe (<strong>22 ± 3</strong>) wurden als <strong>durchschnittlich</strong> kategorisiert, und der Rest unterteilt in die Kategorien klein (von 6 bis 14 Konsonanten), mäßig klein (15-18), mäßig groß (26-33) und groß (34 oder mehr Konsonanten).</p></li>
<li><p><strong>Slowenisch</strong> kann wie <strong>Deutsch</strong> oder Britisches Englisch in die Gruppe mit <strong>durchschnittlich</strong> vielen Konsonantenphonemen (»average«) eingeordnet werden (19&nbsp; Konsantenphoneme: p, t, k, b, d, g, f, v, s, z, s, S, j, Z, x, m, n, r, l).</p></li>
<li><p>Rotokas (West Bougainville; Papua-Neuguinea) hat nur sechs Konsonanten: /p, t, k, b, d, g/. !Xóõ (Southern Khoisan; Botswana) hat 122 Konsonanten, hauptsächlich weil es sehr viele verschiedene Klicklaute gibt, mit denen ein Wort beginnen kann.</p></li>
</ul>
<p>&nbsp;</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="pictures/01b_NSG_Intro_2020-10-07/wals_consonant_inventories.png" class="img-fluid" style="width:100.0%"></p>
</div>
</div>
<p><a href="https://wals.info/">Wals Online</a></p>
<p>In Maddieson (in: Wals 2005) finden wir folgende Angaben zur Größe von <strong>Vokalinventaren</strong> (gemeint sind Vokalphoneme):</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">&nbsp;</th>
<th style="text-align: center;"><strong>Vowel Quality Inventory</strong></th>
<th style="text-align: center;">&nbsp;</th>
<th style="text-align: center;">&nbsp;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1.</td>
<td style="text-align: center;">Small vowel inventory</td>
<td style="text-align: center;">(2-4)</td>
<td style="text-align: center;">92</td>
</tr>
<tr class="even">
<td style="text-align: center;">2.</td>
<td style="text-align: center;">Average vowel inventory</td>
<td style="text-align: center;">(5-6)</td>
<td style="text-align: center;">288</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3.</td>
<td style="text-align: center;">Large vowel inventory</td>
<td style="text-align: center;">(7-14)</td>
<td style="text-align: center;">183</td>
</tr>
<tr class="even">
<td style="text-align: center;">§</td>
<td style="text-align: center;">Total</td>
<td style="text-align: center;">&nbsp;</td>
<td style="text-align: center;">563</td>
</tr>
</tbody>
</table>
<p><a href="https://wals.info/">Wals Online</a></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="pictures/01b_NSG_Intro_2020-10-07/wals_vowel_inventories.png" class="img-fluid" style="width:100.0%"></p>
</div>
</div>
<p>&nbsp;</p>
<ul>
<li><p>Der <strong>Umfang</strong> des kleinsten erfassten Vokalqualitätsinventars ist 2 und des größten 14.</p></li>
<li><p>Es gibt 4 Sprachen in der Stichprobe mit <strong>nur zwei</strong> kontrastierenden Vokalqualitäten. Ein Beispiel für dieses Extrem ist Yimas (Lower Sepik-Ramu; Papua-Neuguinea).«</p></li>
<li><p>Nur eine Sprache in der Stichprobe, <strong>Deutsch</strong>, verwendet 14 Vokalqualitäten (i, I, e, E, a, A, O, o, U, u; y, Y, 9, 2; die Phonemvarianten @ in <em>bitt<u>e</u></em> und 6 in <em>bess<u>er</u> nicht berücksichtigt</em>) »und nur 2 verwenden 13 Vokalqualitäten, nämlich die hier enthaltene Variante des britischen Englisch and Bété (Kru, Niger-Congo; Côte d’Ivoire).</p></li>
<li><p>Deutlich mehr Sprachen haben einen Bestand von <strong>fünf Vokalen</strong> als jede andere Zahl – 188 oder etwas mehr als ein Drittel. Die zweithäufigste Inventargröße sind <strong>sechs Vokalqualitäten</strong> mit 100 Sprachen (oder 17,8% der Stichprobe).</p></li>
<li><p>Vokalqualitätsinventare mit 5 oder 6 Mitgliedern wurden in der Kategorie „Durchschnitt” zusammengefasst, während solche mit 4 oder weniger als „klein” und solche mit 7 oder mehr als „groß” eingestuft werden. Sprachen mit „durchschnittlicher” Vokalinventargröße machen mehr als die Hälfte der Stichprobe aus (51,2 %), etwa ein Drittel (32,5%) hat „große” Vokalqualitätsinventare und nur 16,3 % haben „kleine” Vokalqualitätsinventare.</p></li>
<li><p><strong>Slowenisch</strong> verfügt in betonten Silben über 7 verschiedene Vokalqualitäten, die distinktiv genutzt werden (i, e, E, a, O, o, u) und kann damit (mit nur etwa halb so vielen distinktiv genutzten Vokalqualitäten) in dieselbe Gruppe eingeordnet werden wie <strong>Deutsch</strong> oder <strong>Britisches Englisch</strong>, die (mit 14 bzw. 13 distinktiv genutzten Vokalqualitäten) am oberen Ende dieser Gruppe anzusiedeln sind.</p></li>
<li><p><strong>In unbetonten Silben</strong> ist die Anzahl der distinktiv genutzten Vokalqualitäten gewöhnlich kleiner, so auch im <strong>Slowenischen</strong> (keine hohen oder mittelhohen Vokale i, e, u) und <strong>Deutschen</strong> (lediglich @, 6).</p></li>
</ul>
<p><strong>Konsonanten-Vokal-Verhältnis</strong> in den Sprachen der Welt (Maddieson, in Wals 2005):</p>
<ul>
<li><p>Das Verhältnis wird einfach durch Division der Anzahl der Konsonanten (C) durch die Anzahl der Vokalqualitäten (VQ) berechnet und wird als C/VQ-Verhältnis bezeichnet.</p></li>
<li><p>Die resultierenden Zahlen reichen von einem Tief von nur etwas über 1 bis zu einem Hoch von 29. Der niedrigste Wert unter den 563 Sprachen, für die er berechnet wurde, wird von Andoke (isoliert; Kolumbien) repräsentiert, das 10 Konsonanten und 9 Vokalqualitäten hat. Die höchste Zahl wird von Abkhaz (Nordwestkaukasier; Georgien) repräsentiert, das mit 58 Konsonanten, aber nur 2 Vokalqualitäten analysiert wird. Das Verhältnis bewegt sich somit zwischen 1,11 und 29, aber die häufigeren Werte liegen näher am unteren Ende der Spanne: der Mittelwert beträgt 4,25 und der Median 3,5.</p></li>
<li><p>Die Sprachen wurden in fünf Kategorien eingeteilt, basierend auf der Aufteilung des Bereichs in geeignete Schritte unterhalb, nahe und oberhalb des Medians, um ein Histogramm mit annähernd normaler Verteilung zu erstellen. Sprachen mit einem Verhältnis von 2,0 oder weniger wurden als „niedriges” C/VQ-Verhältnis eingestuft. Diejenigen mit einem Verhältnis über 2,0, aber unter 2,75 wurden als „mäßig niedrig” eingestuft. Personen mit einem Verhältnis von 2,75 oder höher aber kleiner als 4,5 wurden als „durchschnittlich”, solche mit Werten von 4,5 oder höher aber kleiner als 6,5 als „mäßig hoch” und solche mit Werten über 6,5 als „hoch” eingestuft. Nur 10 Sprachen haben Verhältnisse von 12 oder höher.«</p></li>
<li><p><strong>Slowenisch</strong> gehört in die Gruppe »<strong>moderately low</strong>«, <strong>Deutsch</strong> und <strong>Britisches Englisch</strong> aufgrund der vielen distinktiv genutzten Vokalqualitäten in die Gruppe »<strong>low</strong>«. &nbsp;</p></li>
</ul>
<p>&nbsp;</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">&nbsp;</th>
<th style="text-align: center;"><strong>Consonant-Vowel-Ratio</strong></th>
<th style="text-align: center;">&nbsp;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1.</td>
<td style="text-align: center;">Low</td>
<td style="text-align: center;">59</td>
</tr>
<tr class="even">
<td style="text-align: center;">2.</td>
<td style="text-align: center;">Moderately low</td>
<td style="text-align: center;">97</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3.</td>
<td style="text-align: center;">Average</td>
<td style="text-align: center;">234</td>
</tr>
<tr class="even">
<td style="text-align: center;">4.</td>
<td style="text-align: center;">Moderately high</td>
<td style="text-align: center;">102</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5.</td>
<td style="text-align: center;">High</td>
<td style="text-align: center;">71</td>
</tr>
<tr class="even">
<td style="text-align: center;">total</td>
<td style="text-align: center;">563</td>
<td style="text-align: center;">&nbsp;</td>
</tr>
</tbody>
</table>
<p><a href="https://wals.info/">Wals Online</a></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="pictures/01b_NSG_Intro_2020-10-07/wals_vowel_consonant_ratio.png" class="img-fluid" style="width:100.0%"></p>
</div>
</div>


<!-- -->

<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography" style="display: none">
<div id="ref-drosdowski1995duden" class="csl-entry" role="doc-biblioentry">
Drosdowski, Günther. 1995. <em>Duden" Grammatik der deutschen Gegenwartssprache"</em>. Bibliograph. Institut.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopiert");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./phonetik.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Aufgabenbereich der Phonetik</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./artikulation.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Artikulatorische Phonetik</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Quellcode</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Aufgabenbereich der Phonemik</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>Die Phonemik erforscht Lautsysteme. Ihre Aufgabe besteht also darin, "die Beziehungen der Laute einer gegebenen Sprache zueinander zu analysieren, um so das Lautsystem zu beschreiben." (SSM 1: 2) In der Tagmemik, einer wichtigen Richtung des amerikanischen Strukturalismus (Hauptvertreter K. L. Pike), werden alle sprachlichen Einheiten unter drei Gesichtspunkten untersucht:</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Opposition,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Variation und</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Distribution.</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">### Opposition</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>Die Wortpaare (oder besser: Lautfolgen) in den folgenden Beispielen unterscheiden sich jeweils nur durch einen Laut. Diejenigen Laute, die sich voneinander unterscheiden (also distinktive phonetische Merkmale aufweisen), stehen in Opposition (nach einer anderen Ausdrucksweise "in paradigmatischem Kontrast") zueinander, womit gesagt sein soll, daß sie bedeutungsunterscheidende Funktion haben.</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>(8) Deutsch: <span class="sc">\[</span>lant<span class="sc">\]</span> "Land" vs. <span class="sc">\[</span>vant<span class="sc">\]</span> "Wand"\</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    $$</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    \frac{<span class="co">[</span><span class="ot">lant</span><span class="co">]</span>}{<span class="co">[</span><span class="ot">vant</span><span class="co">]</span>}</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    $$</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>(9) Slowenisch: <span class="sc">\[</span>ko:s<span class="sc">\]</span> "kos" (Stück) vs. <span class="sc">\[</span>vo:s<span class="sc">\]</span> "voz" (Wagen)\</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    $$</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    \frac{<span class="co">[</span><span class="ot">ko:s</span><span class="co">]</span>}{<span class="co">[</span><span class="ot">vo:s</span><span class="co">]</span>}</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>    $$</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>(10) Englisch: <span class="sc">\[</span>fɪʃ<span class="sc">\]</span> "fish" (Fisch) vs. <span class="sc">\[</span>dɪʃ<span class="sc">\]</span> "dish" (Gefäß).\</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>     $$</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>     \frac{<span class="co">[</span><span class="ot">fɪʃ</span><span class="co">]</span>}{<span class="co">[</span><span class="ot">dɪʃ</span><span class="co">]</span>}</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>     $$</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>Somit müssen <span class="sc">\[</span>l<span class="sc">\]</span> und <span class="sc">\[</span>v<span class="sc">\]</span> im deutschen Beispiel, <span class="sc">\[</span>k<span class="sc">\]</span> und <span class="sc">\[</span>v<span class="sc">\]</span> im slowenischen und <span class="sc">\[</span>f<span class="sc">\]</span> und <span class="sc">\[</span>d<span class="sc">\]</span> im englischen jeweils zwei Phonemen zugeordnet werden: in (8) den Phonemen /l/ und /v/, in (9) den Phonemen /k/ und /v/ und in (10) den Phonemen /f/ und /d/.</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>Opposition ist eine **paradigmatische Beziehung**, Kontrast dagegen eine syntagmatische. Eine Opposition ist eine **symmetrische Beziehung** zwischen sprachlichen Lauten. In den Lautfolgen der Wörter \&lt;fast\&gt; und \&lt;Rast\&gt; steht der Obstruent \[f\] in Opposition zum Liquid \[R\] und umgekehrt. **Kontrast** ist dagegen eine **asymmetrische Beziehung** zwischen sprachlichen Lauten (vgl. Eisenberg 1998: 88). In einer Form wie \&lt;Frau\&gt; steht der Liquid /r/ in Kontrast zum Obstruenten /f/, während der Obstruent /f/ in dieser Position nicht in Kontrast zum Liquid /r/ stehen kann, da eine (einsilbige) Form wie \[rfao\] nicht vorkommt. In anderen Umgebungen kontrastiert der Obstruent durchaus mit dem Liquid*,* z.B. in \[Wurf\], aber der Liquid nicht mit dem Obstruenten \[Wufr\]. Beide Lautfolgen (d.h. \[fr\] und \[rf\]) sind somit an unterschiedliche Kontexte gebunden. Der Kontrastbegriff ist die Grundlage für die Ermittlung der **phonotaktischen Kombinationsmöglichkeiten** (Lautkombinatorik) in einer Sprache. Als operationale Verfahren zur Ermittlung einer **Opposition** verwenden wir die **Kommutations- oder Substitutionsprobe**, zur Ermittlung eines **Kontrastes** dagegen die **Permutations- oder Verschiebeprobe**. Die in den oben angeführten Beispielen durchgeführte Kommutationsprobe nennt man übrigens auch den **Minimalpaartest**. (vgl. auch in der Dudengrammatik <span class="co">[</span><span class="ot">@drosdowski1995duden : 32-33</span><span class="co">]</span> über die funktionalen Eigenschaften Opposition und Kontrast am Beispiel des Wortes <span class="sc">\&lt;</span>Markt<span class="sc">\&gt;</span>).</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="fu">### Variation</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>Zwei verschiedene Laute einer Sprache stehen nicht immer in Opposition zueinander. Können verschiedene Laute nicht als Phoneme eingeordnet werden, dann besteht die Möglichkeit, dass es sich um Varianten eines einzigen Phonems (auch **Allophone** genannt) handelt. **Phonemvariation** kann **frei** oder **stellungsgebunden** sein.</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>(11) Deutsch: <span class="sc">\[</span>reː.ɡən<span class="sc">\]</span> vs. <span class="sc">\[</span>Reː.ɡən<span class="sc">\]</span> vs. <span class="sc">\[</span>ʁeː.ɡən<span class="sc">\]</span> "Regen"</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>(12) Slowenisch: <span class="sc">\[</span>ta.nək<span class="sc">\]</span> tanek "dünn", masc. vs. <span class="sc">\[</span>taŋ.ka<span class="sc">\]</span> tanka "dünn", fem.</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>Im deutschen Wort <span class="sc">\&lt;</span>Regen<span class="sc">\&gt;</span> (11) kann das Phonem /r/ verschiedentlich realisiert werden, ohne dadurch die Bedeutung der Lautfolge zu verändern. Im Deutschen sind die drei r-Laute <span class="sc">\[</span>r<span class="sc">\]</span>, <span class="sc">\[</span>R<span class="sc">\]</span> und <span class="sc">\[</span>ʁ<span class="sc">\]</span> freie Varianten eines einzigen Phonems, d.h. **fakultative Allophone** des Phonems /r/. Auch im Slowenischen können die oben genannten r-Laute frei variieren, ohne die Wortbedeutung zu verändern. In der slowenischen Standardsprache ist allerdings im Unterschied zur deutschen nur das alveolar apikale <span class="sc">\[</span>r<span class="sc">\]</span> üblich, das auch als Zungenspitzen-r bekannt ist. In einer anderen Sprache können verschieden realisierte r-Laute allerdings auch in Opposition zueinander stehen und somit als zwei verschiedene Phoneme eingeordnet werden (z.B. im Spanischen ein langer und ein kurzer r-Laut).</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>Das Phonem /n/ wird im Slowenischen (12) je nach Lautumgebung als dental-alveolares <span class="sc">\[</span>n<span class="sc">\]</span> oder als velar-postdorsales <span class="sc">\[</span>ŋ<span class="sc">\]</span> realisiert. Vor einem Vokal wird beispielsweise die erste Variante ausgesprochen, vor den velaren Obstruenten <span class="sc">\[</span>k<span class="sc">\]</span>, <span class="sc">\[</span>g<span class="sc">\]</span> und <span class="sc">\[</span>x<span class="sc">\]</span> die letztere (Toporišič ^2^1991: 71). Das Phonem /n/ weist demnach im Slowenischen (neben anderen hier nicht aufgeführten) zumindest zwei **stellungsbedingte Allophone** (positionsabhängige, stellungsgebundene oder kombinatorische Allophone) auf. Im Slowenischen sind die beiden Allophone **komplementär verteilt**, d.h. daß das <span class="sc">\[</span>n<span class="sc">\]</span> nicht in allen Lautumgebungen vorkommt, in denen <span class="sc">\[</span>ŋ<span class="sc">\]</span> auftritt, und umgekehrt.</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>Auch im Deutschen kommt der velare Nasalkonsonant <span class="sc">\[</span>ŋ<span class="sc">\]</span> ebenfalls nicht in allen Lautumgebungen vor (wie im Slowenischen ist er im Silbenanlaut ausgeschlossen), aber an der Silbengrenze zwischen Vokalen steht er in Opposition zum alveolaren Nasalkonsonant <span class="sc">\[</span>n<span class="sc">\]</span> (vgl. <span class="sc">\&lt;</span>Wanne<span class="sc">\&gt;</span> vs. <span class="sc">\&lt;</span>Wange<span class="sc">\&gt;</span>). Die Tatsache, dass mit Hilfe eines Minimalpaartests eine Opposition zwischen den beiden deutschen Nasalkonsonanten gefunden werden konnte, kann man als Argument für die Unterscheidung zweier Phoneme werten. Dagegen spricht, dass der velare Nasalkonsonant in weniger Lautumgebungen vorkommt als der alveolare Nasalkonsonant.</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>Der phonetische Unterschied in slowenischen Beispiel (12) ist demnach durch die Lautumgebung bestimmt. Man kann also von der lautlichen Umgebung her schließen, welchen phonetischen Wert das Phonem /n/ in dieser Umgebung hat. Somit sind die beiden Laute (Phone) im Slowenischen Varianten einer Lauteinheit (eines Phonems), und es genügt, ein einziges phonemisches Zeichen /n/ für beide phonetischen Varianten <span class="sc">\[</span>n<span class="sc">\]</span> und <span class="sc">\[</span>ŋ<span class="sc">\]</span> anzusetzen. Im Slowenischen wird dieses Verhalten auch in der Ortographie (Rechtschreibung) ausgedrückt, denn beide Realisierungsformen des Phonems werden durch das gleiche Graphem wiedergegeben (auch in Eigennamen, vgl. (13)).</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>(13) <span class="sc">\&lt;</span>Ana<span class="sc">\&gt;</span> vs. <span class="sc">\&lt;</span>Anka<span class="sc">\&gt;</span>.</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>Im Deutschen spricht die Orthographie nicht dafür, die beiden Nasalkonsonanten einem einzigen Phonem zuzuordnen, denn die beiden Laute werden im einheimischen Wortschatz durch unterschiedliche Grapheme wiedergegeben: so wird der alveolare Nasalkonsonant mit dem Graphem <span class="sc">\&lt;</span>n<span class="sc">\&gt;</span> wiedergegeben (wie z.B. in <span class="sc">\&lt;</span>Biene, Wanne<span class="sc">\&gt;</span>), während dem velaren Nasalkonsonanten das Graphem <span class="sc">\&lt;</span>ng<span class="sc">\&gt;</span> zugeordnet wird (wie z.B. in <span class="sc">\&lt;</span>Wange, Klinge, Zunge<span class="sc">\&gt;</span>). Die beiden deutschen Nasalkonsonanten könnten eher als zwei verschiedene Phoneme gewertet werden, die beiden slowenischen Nasalkonsonanten dagegen eher als ein Phonem (mit stellungsbedingter Phonemvariation).</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a><span class="fu">### Distribution</span></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>Beim Vergleich zweier Sprachen kann man oft feststellen, dass in beiden zwar derselbe Laut (oder zwei sehr ähnliche Laute) vorkommt, aber jeweils in unterschiedlicher Position. Der betreffende Laut hat in beiden Sprachen also eine unterschiedliche Verteilung oder Distribution. Dieser Umstand soll am Beispiel des velaren Nasalkonsonanten illustriert werden.</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>Der **velare Nasalkonsonant** \[ŋ\] kommt in der **deutschen Standardsprache** in den folgenden Positionen vor:</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>im Wort- und Silbenauslaut nach ungespannten Vokalen (z.B. <span class="sc">\&lt;</span>Ding, eng, Gang, Gong, Dung<span class="sc">\&gt;</span>);</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>im Wort- und Silbenauslaut als Folge der Schwa-Tilgung und der Assimilation nach <span class="sc">\[</span>g<span class="sc">\]</span> und <span class="sc">\[</span>k<span class="sc">\]</span> in derselben Silbe (z.B. <span class="sc">\&lt;</span>fragen, packen<span class="sc">\&gt;</span>);</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>im Silbenauslaut vor <span class="sc">\[</span>k<span class="sc">\]</span> im Anlaut der nächsten Silbe (z.B. <span class="sc">\&lt;</span>trin-ken<span class="sc">\&gt;</span>);</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>im Silbenauslaut vor <span class="sc">\[</span>g<span class="sc">\]</span> im Anlaut der nächsten Silbe, aber nur in Lehnwörtern (z.B. <span class="sc">\&lt;</span>Tan-go, Un-garn, Lin-gu-ist<span class="sc">\&gt;</span>);</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>im Wort- und Silbeninlaut vor <span class="sc">\[</span>k<span class="sc">\]</span> in derselben Silbe (z.B. <span class="sc">\&lt;</span>Schank<span class="sc">\&gt;</span>);</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>im Inlaut als sogenanntes Silbengelenk (d.h. gleichzeitig im Auslaut der ersten Silbe und im Anlaut der zweiten) vor Schwa <span class="sc">\[</span>ə<span class="sc">\]</span> (z.B. <span class="sc">\&lt;</span>hängen<span class="sc">\&gt;</span>) oder als Folge von Assimilation vor sonantischem <span class="sc">\[</span>l̩<span class="sc">\]</span> (z.B. kling(e)ln).</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>In der **slowenischen Standardsprache** tritt der **velare Nasalkonsonant** <span class="sc">\[</span>ŋ<span class="sc">\]</span> in den folgenden Positionen auf:</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>im Silbenauslaut nach ungespannten Vokalen vor <span class="sc">\[</span>g<span class="sc">\]</span>, <span class="sc">\[</span>k<span class="sc">\]</span> und <span class="sc">\[</span>x<span class="sc">\]</span> in der nächsten Silbe (z.B. <span class="sc">\&lt;</span>An-hovo, Kon-go, Can-kar<span class="sc">\&gt;</span>);</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>im Silbeninlaut nach ungespannten Vokalen vor <span class="sc">\[</span>k<span class="sc">\]</span> in derselben Silbe (z.B. <span class="sc">\&lt;</span>tank<span class="sc">\&gt;</span>).</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>Aus dieser Gegenüberstellung ist ersichtlich, daß die **Distribution** des velaren Nasalkonsonanten **im Slowenischen eingeschränkter** ist als im Deutschen, denn im Slowenischen kann er nicht stehen:</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>im Silben- oder Wortauslaut, wenn kein <span class="sc">\[</span>k<span class="sc">\]</span> in derselben oder der nächsten Silbe folgt;</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>im Inlaut vor Schwa <span class="sc">\[</span>ə<span class="sc">\]</span> oder sonantischem <span class="sc">\[</span>l̩<span class="sc">\]</span>;</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>im Auslaut nach <span class="sc">\[</span>g<span class="sc">\]</span> und <span class="sc">\[</span>k<span class="sc">\]</span> (d.h. aufgrund von Schwa-Reduktion und regressiver Nasalassimilation an einen velaren Obstruenten wie im deutschen Verb <span class="sc">\&lt;</span>fragen<span class="sc">\&gt;</span>).</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>**Tabelle 2: Distribution des Nasalkonsonaten \[ŋ\] im Deutschen und Slowenischen**</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>+-----------------------------------+--------------------------------------------------------------+-------------------------+</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>|                                   | **Deutsch**                                                  | **Slowenisch**          |</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>+===================================+==============================================================+=========================+</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>| **Wort- u.** **Silbenanlaut**     | &nbsp;                                                            | &nbsp;                       |</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>+-----------------------------------+--------------------------------------------------------------+-------------------------+</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a>| **Wort- u.** **Silbeninlaut**     | vor <span class="sc">\[</span>k<span class="sc">\]</span>                                                    | vor <span class="sc">\[</span>k<span class="sc">\]</span>               |</span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>+-----------------------------------+--------------------------------------------------------------+-------------------------+</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a>| **Wortinlaut** **(Silbengelenk)** | vor <span class="sc">\[</span>ə<span class="sc">\]</span> und <span class="sc">\[</span>l̩<span class="sc">\]</span>                                          |                         |</span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>+-----------------------------------+--------------------------------------------------------------+-------------------------+</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a>| **Silbenauslaut**                 | Vokal:                                                       | Vokal:                  |</span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>|                                   |                                                              |                         |</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a>|                                   | vor <span class="sc">\[</span>k<span class="sc">\]</span>                                                    | vor <span class="sc">\[</span>k<span class="sc">\]</span>, <span class="sc">\[</span>g<span class="sc">\]</span>, <span class="sc">\[</span>x<span class="sc">\]</span> |</span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>+-----------------------------------+--------------------------------------------------------------+-------------------------+</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>| **Wortauslaut**                   | nach <span class="sc">\[</span>g<span class="sc">\]</span> und <span class="sc">\[</span>k<span class="sc">\]</span> in unbetonter Silbe (bei Schwa-Tilgung) |                         |</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>+-----------------------------------+--------------------------------------------------------------+-------------------------+</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>&nbsp;</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>In einem Fall ist die Distribution des velaren Nasalkonsonanten im Deutschen jedoch eingeschränkter, denn im Slowenischen kann der velare Nasalkonsonant vor <span class="sc">\[</span>x<span class="sc">\]</span> in der nächsten Silbe auftreten, im Deutschen jedoch nicht.</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>Beide Sprachen haben u.a. gemeinsam, daß der velare Nasalkonsonant nicht im Silbenanlaut vorkommen kann. Diese Möglichkeit besteht in anderen Sprachen, z.B. im Kulunge, einer Sprache Nepals (SSM 1: 3).</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a><span class="in">```{r echo=FALSE, message=FALSE, warning=FALSE, out.width="100%"}</span></span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(</span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a>  <span class="st">"pictures/01b_NSG_Intro_2020-10-07/wals_velar_nasal.png"</span>)</span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Wals Online</span><span class="co">](https://wals.info/)</span></span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>Im Rahmen der Lautdistribution wird auch die Häufigkeit des Vorkommens eines Lautes untersucht, anhand derer sich oft charakteristische Unterschiede zwischen Sprachen feststellen lassen (SSM 1: 3). So tritt z.B. der stimmhafte postalveolare Frikativ <span class="sc">\[</span>ʒ<span class="sc">\]</span> im Deutschen nur in wenigen Lehnwörtern auf (z.B. <span class="sc">\&lt;</span><span class="co">[</span><span class="ot">G</span><span class="co">]</span>{.underline}enie, Gara<span class="co">[</span><span class="ot">g</span><span class="co">]</span>{.underline}e<span class="sc">\&gt;</span>) und hat daher eine eher periphere Stellung im deutschen Phonemsystem. Im Französischen oder im Slowenischen tritt dieser stimmhafte Frikativ jedoch in einer viel größeren Anzahl von Wörtern auf und gehört eher zum Kern des französischen bzw. slowenischen Phonemsystems (z.B. franz. <span class="sc">\&lt;</span><span class="co">[</span><span class="ot">j</span><span class="co">]</span>{.underline}e<span class="sc">\&gt;</span> "ich", <span class="sc">\&lt;</span><span class="co">[</span><span class="ot">j</span><span class="co">]</span>{.underline}our<span class="sc">\&gt;</span> "Tag", <span class="sc">\&lt;</span>pi<span class="co">[</span><span class="ot">g</span><span class="co">]</span>{.underline}eon<span class="sc">\&gt;</span> "Taube"; slow. <span class="sc">\&lt;</span><span class="co">[</span><span class="ot">ž</span><span class="co">]</span>{.underline}ena<span class="sc">\&gt;</span> "(Ehe)frau", <span class="sc">\&lt;</span><span class="co">[</span><span class="ot">ž</span><span class="co">]</span>{.underline}oga<span class="sc">\&gt;</span> "Ball", <span class="sc">\&lt;</span><span class="co">[</span><span class="ot">ž</span><span class="co">]</span>{.underline}aba<span class="sc">\&gt;</span> "Frosch").</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a><span class="fu">### Phonem- und Silbeninventare</span></span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a>Zur Orientierung sollen einige Angaben zur Phoneminventargröße herangezogen werden. In der Untersuchung von Ian Maddieson (Consonant Inventories, In: Wals 2005) findet man folgende Angaben zur **Größe von Konsonanteninventaren** in den Sprachen der Welt (gemeint sind Konsonantenphoneme):</span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>|  &nbsp;  | **Consonant Inventory Size** |  &nbsp;  |</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a>|:---:|:----------------------------:|:---:|</span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>| 1<span class="sc">\.</span> |            Small             | 91  |</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>| 2<span class="sc">\.</span> |       Moderately small       | 121 |</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>| 3<span class="sc">\.</span> |           Average            | 181 |</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>| 4<span class="sc">\.</span> |       Moderately large       | 116 |</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a>| 5<span class="sc">\.</span> |            Large             | 53  |</span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a>| \@  |            Total             | 562 |</span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a>&nbsp;</span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Die **typischere Konsonanteninventargröße** liegt in den unteren Zwanzigern, wobei der Mittelwert für die 562 Sprachen 22,7 beträgt, der Modus 22 und der Median 21. Konsonanteninventare in der Nähe dieser Größe (**22 ± 3**) wurden als **durchschnittlich** kategorisiert, und der Rest unterteilt in die Kategorien klein (von 6 bis 14 Konsonanten), mäßig klein (15-18), mäßig groß (26-33) und groß (34 oder mehr Konsonanten).</span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Slowenisch** kann wie **Deutsch** oder Britisches Englisch in die Gruppe mit **durchschnittlich** vielen Konsonantenphonemen (»average«) eingeordnet werden (19&nbsp; Konsantenphoneme: p, t, k, b, d, g, f, v, s, z, s, S, j, Z, x, m, n, r, l).</span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Rotokas (West Bougainville; Papua-Neuguinea) hat nur sechs Konsonanten: /p, t, k, b, d, g/. !Xóõ (Southern Khoisan; Botswana) hat 122 Konsonanten, hauptsächlich weil es sehr viele verschiedene Klicklaute gibt, mit denen ein Wort beginnen kann.</span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a>&nbsp;</span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a><span class="in">```{r echo=FALSE, message=FALSE, warning=FALSE, out.width="100%"}</span></span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>  <span class="st">"pictures/01b_NSG_Intro_2020-10-07/wals_consonant_inventories.png"</span>)</span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Wals Online</span><span class="co">](https://wals.info/)</span></span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a>In Maddieson (in: Wals 2005) finden wir folgende Angaben zur Größe von **Vokalinventaren** (gemeint sind Vokalphoneme):</span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a>|  &nbsp;  | **Vowel Quality Inventory** |   &nbsp;    |  &nbsp;  |</span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a>|:---:|:---------------------------:|:------:|:---:|</span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a>| 1<span class="sc">\.</span> |    Small vowel inventory    | (2-4)  | 92  |</span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a>| 2<span class="sc">\.</span> |   Average vowel inventory   | (5-6)  | 288 |</span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>| 3<span class="sc">\.</span> |    Large vowel inventory    | (7-14) | 183 |</span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a>|  §  |            Total            |   &nbsp;    | 563 |</span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Wals Online</span><span class="co">](https://wals.info/)</span></span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a><span class="in">```{r echo=FALSE, message=FALSE, warning=FALSE, out.width="100%"}</span></span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(</span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a>  <span class="st">"pictures/01b_NSG_Intro_2020-10-07/wals_vowel_inventories.png"</span>)</span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a>&nbsp;</span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Der **Umfang** des kleinsten erfassten Vokalqualitätsinventars ist 2 und des größten 14.</span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Es gibt 4 Sprachen in der Stichprobe mit **nur zwei** kontrastierenden Vokalqualitäten. Ein Beispiel für dieses Extrem ist Yimas (Lower Sepik-Ramu; Papua-Neuguinea).«</span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Nur eine Sprache in der Stichprobe, **Deutsch**, verwendet 14 Vokalqualitäten (i, I, e, E, a, A, O, o, U, u; y, Y, 9, 2; die Phonemvarianten \@ in *bitt[e]{.underline}* und 6 in *bess[er]{.underline} nicht berücksichtigt*) »und nur 2 verwenden 13 Vokalqualitäten, nämlich die hier enthaltene Variante des britischen Englisch and Bété (Kru, Niger-Congo; Côte d'Ivoire).</span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Deutlich mehr Sprachen haben einen Bestand von **fünf Vokalen** als jede andere Zahl -- 188 oder etwas mehr als ein Drittel. Die zweithäufigste Inventargröße sind **sechs Vokalqualitäten** mit 100 Sprachen (oder 17,8% der Stichprobe).</span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Vokalqualitätsinventare mit 5 oder 6 Mitgliedern wurden in der Kategorie „Durchschnitt" zusammengefasst, während solche mit 4 oder weniger als „klein" und solche mit 7 oder mehr als „groß" eingestuft werden. Sprachen mit „durchschnittlicher" Vokalinventargröße machen mehr als die Hälfte der Stichprobe aus (51,2 %), etwa ein Drittel (32,5%) hat „große" Vokalqualitätsinventare und nur 16,3 % haben „kleine" Vokalqualitätsinventare.</span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Slowenisch** verfügt in betonten Silben über 7 verschiedene Vokalqualitäten, die distinktiv genutzt werden (i, e, E, a, O, o, u) und kann damit (mit nur etwa halb so vielen distinktiv genutzten Vokalqualitäten) in dieselbe Gruppe eingeordnet werden wie **Deutsch** oder **Britisches Englisch**, die (mit 14 bzw. 13 distinktiv genutzten Vokalqualitäten) am oberen Ende dieser Gruppe anzusiedeln sind.</span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**In unbetonten Silben** ist die Anzahl der distinktiv genutzten Vokalqualitäten gewöhnlich kleiner, so auch im **Slowenischen** (keine hohen oder mittelhohen Vokale i, e, u) und **Deutschen** (lediglich \@, 6).</span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a>**Konsonanten-Vokal-Verhältnis** in den Sprachen der Welt (Maddieson, in Wals 2005):</span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Das Verhältnis wird einfach durch Division der Anzahl der Konsonanten (C) durch die Anzahl der Vokalqualitäten (VQ) berechnet und wird als C/VQ-Verhältnis bezeichnet.</span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Die resultierenden Zahlen reichen von einem Tief von nur etwas über 1 bis zu einem Hoch von 29. Der niedrigste Wert unter den 563 Sprachen, für die er berechnet wurde, wird von Andoke (isoliert; Kolumbien) repräsentiert, das 10 Konsonanten und 9 Vokalqualitäten hat. Die höchste Zahl wird von Abkhaz (Nordwestkaukasier; Georgien) repräsentiert, das mit 58 Konsonanten, aber nur 2 Vokalqualitäten analysiert wird. Das Verhältnis bewegt sich somit zwischen 1,11 und 29, aber die häufigeren Werte liegen näher am unteren Ende der Spanne: der Mittelwert beträgt 4,25 und der Median 3,5.</span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Die Sprachen wurden in fünf Kategorien eingeteilt, basierend auf der Aufteilung des Bereichs in geeignete Schritte unterhalb, nahe und oberhalb des Medians, um ein Histogramm mit annähernd normaler Verteilung zu erstellen. Sprachen mit einem Verhältnis von 2,0 oder weniger wurden als „niedriges" C/VQ-Verhältnis eingestuft. Diejenigen mit einem Verhältnis über 2,0, aber unter 2,75 wurden als „mäßig niedrig" eingestuft. Personen mit einem Verhältnis von 2,75 oder höher aber kleiner als 4,5 wurden als „durchschnittlich", solche mit Werten von 4,5 oder höher aber kleiner als 6,5 als „mäßig hoch" und solche mit Werten über 6,5 als „hoch" eingestuft. Nur 10 Sprachen haben Verhältnisse von 12 oder höher.«</span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Slowenisch** gehört in die Gruppe »**moderately low**«, **Deutsch** und **Britisches Englisch** aufgrund der vielen distinktiv genutzten Vokalqualitäten in die Gruppe »**low**«. &nbsp;</span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a>&nbsp;</span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a>|   &nbsp;   | **Consonant-Vowel-Ratio** |  &nbsp;  |</span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a>|:-----:|:-------------------------:|:---:|</span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a>|  1<span class="sc">\.</span>  |            Low            | 59  |</span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a>|  2<span class="sc">\.</span>  |      Moderately low       | 97  |</span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a>|  3<span class="sc">\.</span>  |          Average          | 234 |</span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a>|  4<span class="sc">\.</span>  |      Moderately high      | 102 |</span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a>|  5<span class="sc">\.</span>  |           High            | 71  |</span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a>| total |            563            |  &nbsp;  |</span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Wals Online</span><span class="co">](https://wals.info/)</span></span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a><span class="in">```{r echo=FALSE, message=FALSE, warning=FALSE, out.width="100%"}</span></span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(</span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a>  <span class="st">"pictures/01b_NSG_Intro_2020-10-07/wals_vowel_consonant_ratio.png"</span>)</span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a>&nbsp;</span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Lehrveranstaltungsmaterialien, Universität Maribor 2022, Teodor Petrič</div>   
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/tpetric7/">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/TPetric">
      <i class="bi bi-twitter" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>



<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>